# Generated by Django 5.1.1 on 2024-10-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='insured',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='person',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Insured',
        ),
        migrations.DeleteModel(
            name='InsurancePolicy',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
