# Generated by Django 5.1.2 on 2024-10-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_insurancepolicy_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='unique_id',
            field=models.CharField(max_length=50),
        ),
    ]
