# Generated by Django 5.1.2 on 2024-10-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.CharField(max_length=10),
        ),
    ]
