# Generated by Django 5.1.2 on 2024-10-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insured', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insured',
            name='unique_id',
            field=models.CharField(max_length=50),
        ),
    ]
